#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_FILE="${REPO_ROOT}/supabase/config.toml"
PORTS_FILE="${REPO_ROOT}/.ports"
TARGET_DIR="${PWD}"

if [ "${1:-}" != "" ]; then
  TARGET_DIR="$(cd "$1" && pwd)"
fi

TARGET_ENV_FILE="${TARGET_DIR}/.env.local"
TARGET_ENV_BACKUP="${TARGET_DIR}/.env.local.backup"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
  printf "%b%s%b\n" "${GREEN}" "$1" "${NC}"
}

log_warn() {
  printf "%b%s%b\n" "${YELLOW}" "$1" "${NC}"
}

log_error() {
  printf "%b%s%b\n" "${RED}" "$1" "${NC}" >&2
}

is_port_free() {
  local port="$1"

  if command -v lsof >/dev/null 2>&1; then
    if lsof -iTCP:"${port}" -sTCP:LISTEN -Pn >/dev/null 2>&1; then
      return 1
    fi
    return 0
  fi

  if command -v nc >/dev/null 2>&1; then
    if nc -z 127.0.0.1 "${port}" >/dev/null 2>&1; then
      return 1
    fi
    return 0
  fi

  log_error "Neither 'lsof' nor 'nc' is available to check ports."
  exit 1
}

apply_ports_to_config() {
  local api_port="$1"
  local db_port="$2"
  local studio_port="$3"
  local inbucket_port="$4"

  cp "${CONFIG_FILE}" "${CONFIG_FILE}.bak"

  sed -E -i.bak \
    -e "/^\\[api\\]/,/^\\[/{s/^port = [0-9]+$/port = ${api_port}/}" \
    -e "/^\\[db\\]/,/^\\[/{s/^port = [0-9]+$/port = ${db_port}/}" \
    -e "/^\\[studio\\]/,/^\\[/{s/^port = [0-9]+$/port = ${studio_port}/}" \
    -e "/^\\[inbucket\\]/,/^\\[/{s/^port = [0-9]+$/port = ${inbucket_port}/}" \
    "${CONFIG_FILE}"

  rm -f "${CONFIG_FILE}.bak" "${CONFIG_FILE}.bak.bak"
}

# Step 1 - prerequisite checks
log_info "Checking prerequisites..."
if ! docker info >/dev/null 2>&1; then
  log_error "Docker is not running. Please start Docker Desktop and retry."
  exit 1
fi

if ! command -v supabase >/dev/null 2>&1; then
  log_error "Supabase CLI is not installed."
  log_warn "Install with: brew install supabase/tap/supabase"
  log_warn "or: npm install supabase --save-dev"
  exit 1
fi

if ! supabase --version >/dev/null 2>&1; then
  log_error "Supabase CLI is installed but not working correctly."
  exit 1
fi

# Step 2 - dynamic port selection
log_info "Selecting free port block..."
BASE=54321
SELECTED=0

for offset in 0 $(seq 10 10 980); do
  local_base=$((BASE + offset))
  api_port="${local_base}"
  db_port="$((local_base + 1))"
  studio_port="$((local_base + 2))"
  inbucket_port="$((local_base + 3))"

  if is_port_free "${api_port}" && is_port_free "${db_port}" && is_port_free "${studio_port}" && is_port_free "${inbucket_port}"; then
    SELECTED=1
    break
  fi
done

if [ "${SELECTED}" -ne 1 ]; then
  log_error "No free port block found from 54321 upwards."
  exit 1
fi

cat > "${PORTS_FILE}" <<EOP
API_PORT=${api_port}
DB_PORT=${db_port}
STUDIO_PORT=${studio_port}
INBUCKET_PORT=${inbucket_port}
EOP

apply_ports_to_config "${api_port}" "${db_port}" "${studio_port}" "${inbucket_port}"
log_info "Using ports: API=${api_port}, DB=${db_port}, Studio=${studio_port}, Inbucket=${inbucket_port}"

# Step 3 - start Supabase and parse output
log_info "Starting Supabase..."
start_output="$(cd "${REPO_ROOT}" && supabase start 2>&1)" || {
  log_error "supabase start failed"
  printf "%s\n" "${start_output}" >&2
  exit 1
}

api_url="$(printf "%s\n" "${start_output}" | sed -n 's/^ *API URL: *//p' | tail -n1)"
anon_key="$(printf "%s\n" "${start_output}" | sed -n 's/^ *anon key: *//p' | tail -n1)"
service_role_key="$(printf "%s\n" "${start_output}" | sed -n 's/^ *service_role key: *//p' | tail -n1)"

if [ -z "${api_url}" ]; then
  api_url="http://127.0.0.1:${api_port}"
fi

if [ -z "${anon_key}" ] || [ -z "${service_role_key}" ]; then
  log_warn "Could not parse keys from start output. Falling back to 'supabase status'."
  status_output="$(cd "${REPO_ROOT}" && supabase status 2>&1 || true)"
  anon_key="${anon_key:-$(printf "%s\n" "${status_output}" | sed -n 's/^ *anon key: *//p' | tail -n1)}"
  service_role_key="${service_role_key:-$(printf "%s\n" "${status_output}" | sed -n 's/^ *service_role key: *//p' | tail -n1)}"
fi

if [ -z "${anon_key}" ] || [ -z "${service_role_key}" ]; then
  log_error "Could not determine anon/service role keys."
  exit 1
fi

# Step 4 - write .env.local
if [ -f "${TARGET_ENV_FILE}" ]; then
  cp "${TARGET_ENV_FILE}" "${TARGET_ENV_BACKUP}"
  log_warn "Existing .env.local backed up to ${TARGET_ENV_BACKUP}"
fi

cat > "${TARGET_ENV_FILE}" <<EOF_ENV
# Generated by localSupabaseDB scripts/setup.sh
# For Supabase Cloud, replace these values with your cloud project values.
NEXT_PUBLIC_SUPABASE_URL=${api_url}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon_key}
SUPABASE_SERVICE_ROLE_KEY=${service_role_key}
EOF_ENV

log_info "Created ${TARGET_ENV_FILE}"

printf "\n"
log_info "Setup complete"
printf "- API URL: %s\n" "${api_url}"
printf "- Studio URL: %s\n" "http://127.0.0.1:${studio_port}"
printf "- Inbucket URL: %s\n" "http://127.0.0.1:${inbucket_port}"
printf "- Port config: %s\n" "${PORTS_FILE}"
printf "\nNext steps:\n"
printf "1) Update site_url in %s to your Next.js app URL.\n" "${CONFIG_FILE}"
printf "2) Start your Next.js app and use %s.\n" "${TARGET_ENV_FILE}"
